import Document, { Html, Head, Main, NextScript } from 'next/document';

export default class MyDocument extends Document {
  render() {
    return (
        <Html lang='pt-BR'>
            <Head>
                <meta charSet="UTF-8"/>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <link href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@200;400;600;700&display=swap" rel="stylesheet" />
                <link href='https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css' rel='stylesheet' />
            </Head>

            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
        
    )
  }
}